name: Pak file build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: srv

    env:
      PAK_KEY: ${{ secrets.PAK_KEY }}

    steps:
    - name: Fetch sources with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Pre-run build script
      run: chmod +x "${{ github.workspace }}/.github/scripts/build.sh"
    - name: Build
      run: "${{ github.workspace }}/.github/scripts/build.sh"