name: Pak file build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: srv

    env:
      PAK_KEY: ${{ secrets.PAK_KEY }}

    steps:
    - name: Pre-fetch sources
      uses: actions/create-github-app-token@v1
      id: app_token
      with:
        app-id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
        private-key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Fetch sources with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ steps.app_token.outputs.token }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x
    - name: Pre-run build script
      run: chmod +x "${{ github.workspace }}/.github/scripts/build.sh"
    - name: Build
      run: "${{ github.workspace }}/.github/scripts/build.sh"