name: Pak file build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    env:
      PAK_KEY: ${{ secrets.PAK_KEY }}

    steps:
    - name: Set vars
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Pre-fetch sources
      uses: actions/create-github-app-token@v1
      id: app_token
      with:
        app-id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
        private-key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Fetch sources with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ steps.app_token.outputs.token }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: bash -c "${{ github.workspace }}/.github/scripts/build.sh \"${{ github.workspace }}\""
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: v${{ steps.vars.outputs.sha_short }}
        tag_name: v${{ steps.vars.outputs.sha_short }}
        token: ${{ steps.app_token.outputs.token }}
        files: |
          pakchunk0-1.0.0-1.1.0-WindowsNoEditor_10000_P.pak
          pakchunk0-1.0.0-1.1.0-WindowsNoEditor_10000_P.pak.sha256